export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED"

export const GET_USER_PROFILE_USER_REQUEST = "GET_USER_PROFILE_USER_REQUEST"
export const GET_USER_PROFILE_USER_SUCCESS = "GET_USER_PROFILE_USER_SUCCESS"
export const GET_USER_PROFILE_USER_FAILED = "GET_USER_PROFILE_USER_FAILED"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED"

export const FIND_USER_BY_ID_REQUEST = "FIND_USER_BY_ID_REQUEST"
export const FIND_USER_BY_ID_SUCCESS = "FIND_USER_BY_ID_SUCCESS"
export const FIND_USER_BY_ID_FAILED = "FIND_USER_BY_ID_FAILED"

export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST"
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS"
export const FOLLOW_USER_FAILED = "FOLLOW_USER_FAILED"

export const LOGOUT = "LOGOUT"