export const TWEET_CREATE_REQUEST = "TWEET_CREATE_REQUEST"
export const TWEET_CREATE_SUCCESS = "TWEET_CREATE_SUCCESS"
export const TWEET_CREATE_FAILED = "TWEET_CREATE_FAILED"

export const TWEET_DELETE_REQUEST = "TWEET_DELETE_REQUEST"
export const TWEET_DELETE_SUCCESS = "TWEET_DELETE_SUCCESS"
export const TWEET_DELETE_FAILED = "TWEET_DELETE_FAILED"

export const GET_ALL_TWEETS_REQUEST = "GET_ALL_TWEETS_REQUEST"
export const GET_ALL_TWEETS_SUCCESS = "GET_ALL_TWEETS_SUCCESS"
export const GET_ALL_TWEETS_FAILED = "GET_ALL_TWEETS_FAILED"

export const GET_USERS_TWEET_REQUEST = "GET_USERS_TWEET_REQUEST"
export const GET_USERS_TWEET_SUCCESS = "GET_USERS_TWEET_SUCCESS"
export const GET_USERS_TWEET_FAILED = "GET_USERS_TWEET_FAILED"

export const USER_LIKE_TWEET_REQUEST = "USER_LIKE_TWEET_REQUEST"
export const USER_LIKE_TWEET_SUCCESS = "USER_LIKE_TWEET_SUCCESS"
export const USER_LIKE_TWEET_FAILED = "USER_LIKE_TWEET_FAILED"

export const LIKE_TWEET_REQUEST = "LIKE_TWEET_REQUEST"
export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS"
export const LIKE_TWEET_FAILED = "LIKE_TWEET_FAILED"

export const FIND_TWEET_BY_ID_REQUEST = "FIND_TWEET_BY_ID_REQUEST"
export const FIND_TWEET_BY_ID_SUCCESS = "FIND_TWEET_BY_ID_SUCCESS"
export const FIND_TWEET_BY_ID_FAILED = "FIND_TWEET_BY_ID_FAILED"

export const REPLY_TWEET_REQUEST = "REPLY_TWEET_REQUEST"
export const REPLY_TWEET_SUCCESS = "REPLY_TWEET_SUCCESS"
export const REPLY_TWEET_FAILED = "REPLY_TWEET_FAILED"

export const RETWEET_REQUEST = "RETWEET_REQUEST"
export const RETWEET_SUCCESS = "RETWEET_SUCCESS"
export const RETWEET_FAILED = "RETWEET_FAILED"
